'------------------------------------------------------------------------------
' <autogeneratedinfo> 
'     This code was generated by: 
'           WJSWizard version: 8.1106.29.0
' 
'     FormType   :  
'     FormUID    : 
'     폼  설  명 : 
'     메뉴리스트 : 
'     관련레포트 : 
'     작  성  자 : 
'     최초작성일 : 2016-10-13 오전 10:19:03 
'     최종수정자 : 
'     최종수정일 : 
'     주요변경로그 : 
' 
' 
' </autogeneratedinfo>---------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:2.0.50727.5485
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports AddOnBase
Imports SAPbobsCOM
Imports SAPbouiCOM
Imports System.Runtime.InteropServices
Imports WJS.COMM


Public Class WJS_FIF0011_DEV
    Inherits B1Frm
    Implements IDisposable

    Private oGrid As SAPbouiCOM.Grid
    Private oButton As SAPbouiCOM.Button
    Private oOptionBtn As SAPbouiCOM.OptionBtn
    Private oComboBox As SAPbouiCOM.ComboBox
    Private oForm As SAPbouiCOM.Form
    Private oEditText As SAPbouiCOM.EditText

    Private disposedValue As Boolean = False

    Public Sub New()
        MyBase.New("2102055011", "WJS_FIF0011_DEV", True)
    End Sub

    <B1Listener(BoEventTypes.et_MENU_CLICK, True, ActionType.Mnu)> _
    Public Overridable Function ET_BFMenuClick(ByVal pVal As MenuEvent) As Boolean
        'GENERATED CODE
        'ADD YOUR ACTION CODE HERE ...
        Return Me.LoadForm
    End Function

    <B1Listener(BoEventTypes.et_MENU_CLICK, False, ActionType.Mnu)> _
    Public Overridable Sub ET_AFMenuClick(ByVal pVal As MenuEvent)
        'GENERATED CODE
        oForm = B1Connections.theAppl.Forms.ActiveForm
        oForm.Freeze(True)
        Me.FormInit(oForm)
        oForm.Freeze(False)
        'ADD YOUR ACTION CODE HERE ...
    End Sub

    Friend Sub Sub_FormInit(ByVal pParm As Object)

        Me.LoadForm()

        oForm = B1Connections.theAppl.Forms.ActiveForm
        oForm.Freeze(True)

        ''Initialize.....
        Call DataBinded(oForm)
        'Call LabelInit(oForm)
        Call Form_Default(oForm, pParm)
        'Call MenuSetting(oForm)

        Call AddChooseFromList(oForm)


        oForm.Freeze(False)

        oForm.Items.Item("btnFIND").Click(BoCellClickType.ct_Regular)

        'FindData(false)
    End Sub

    Private Sub FormInit(ByVal oForm As SAPbouiCOM.Form)
        ''Initialize.....
        Call DataBinded(oForm)
        'Call LabelInit(oForm)
        Call Form_Default(oForm)
        'Call MenuSetting(oForm)

        Call AddChooseFromList(oForm)

        'FindData(false)
    End Sub


    <B1Listener(BoEventTypes.et_FORM_UNLOAD, False, ActionType.Frm)> _
    Public Overridable Sub ET_AFFormUnload(ByVal pVal As ItemEvent)
        'ADD YOUR ACTION CODE HERE ...
        Me.ClearUnManagedObject()
    End Sub

    Private Sub ClearUnManagedObject()

        If (Not (oGrid) Is Nothing) Then Marshal.ReleaseComObject(oGrid)
        oGrid = Nothing

        If (Not (oButton) Is Nothing) Then Marshal.ReleaseComObject(oButton)
        oButton = Nothing

        If (Not (oOptionBtn) Is Nothing) Then Marshal.ReleaseComObject(oOptionBtn)
        oOptionBtn = Nothing

        If (Not (oComboBox) Is Nothing) Then Marshal.ReleaseComObject(oComboBox)
        oComboBox = Nothing

        If (Not (oEditText) Is Nothing) Then Marshal.ReleaseComObject(oEditText)
        oEditText = Nothing
        If (Not (oForm) Is Nothing) Then
            Marshal.ReleaseComObject(oForm)
        End If
        oForm = Nothing
        'ADD YOUR ACTION CODE HERE ...
        System.GC.Collect()
        System.GC.WaitForPendingFinalizers()
    End Sub
    Private Sub DataBinded(ByVal oForm As SAPbouiCOM.Form)

        '-------------------------------------------------------------------------------
        'UserDateSource 선언 시작
        '-------------------------------------------------------------------------------
        Call oForm.DataSources.UserDataSources.Add("edtDATEF", BoDataType.dt_DATE)
        Call oForm.DataSources.UserDataSources.Add("edtDATET", BoDataType.dt_DATE)
        Call oForm.DataSources.UserDataSources.Add("cboACTTYPE", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("cboACTLVL", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("cboBPTYPE", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("cboBPGRP", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("edtACCTCDF", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("edtACCTCDT", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("edtACCTNMF", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("edtACCTNMT", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("edtBPCDF", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("edtBPCDT", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("edtBPNMF", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("edtBPNMT", BoDataType.dt_SHORT_TEXT)
        Call oForm.DataSources.UserDataSources.Add("chkZEROYN", BoDataType.dt_SHORT_TEXT)
        '-------------------------------------------------------------------------------
        'UserDateSource 선언 끝
        '-------------------------------------------------------------------------------

        '-------------------------------------------------------------------------------
        '폼콘트롤과 UserDateSource 바인딩 시작
        '-------------------------------------------------------------------------------
        Call oForm.Items.Item("edtDATEF").Specific.DataBind.SetBound(True, "", "edtDATEF")
        Call oForm.Items.Item("edtDATET").Specific.DataBind.SetBound(True, "", "edtDATET")
        Call oForm.Items.Item("cboACTTYPE").Specific.DataBind.SetBound(True, "", "cboACTTYPE")
        Call oForm.Items.Item("cboACTLVL").Specific.DataBind.SetBound(True, "", "cboACTLVL")
        Call oForm.Items.Item("cboBPTYPE").Specific.DataBind.SetBound(True, "", "cboBPTYPE")
        Call oForm.Items.Item("cboBPGRP").Specific.DataBind.SetBound(True, "", "cboBPGRP")
        Call oForm.Items.Item("edtACCTCDF").Specific.DataBind.SetBound(True, "", "edtACCTCDF")
        Call oForm.Items.Item("edtACCTCDT").Specific.DataBind.SetBound(True, "", "edtACCTCDT")
        Call oForm.Items.Item("edtACCTNMF").Specific.DataBind.SetBound(True, "", "edtACCTNMF")
        Call oForm.Items.Item("edtACCTNMT").Specific.DataBind.SetBound(True, "", "edtACCTNMT")
        Call oForm.Items.Item("edtBPCDF").Specific.DataBind.SetBound(True, "", "edtBPCDF")
        Call oForm.Items.Item("edtBPCDT").Specific.DataBind.SetBound(True, "", "edtBPCDT")
        Call oForm.Items.Item("edtBPNMF").Specific.DataBind.SetBound(True, "", "edtBPNMF")
        Call oForm.Items.Item("edtBPNMT").Specific.DataBind.SetBound(True, "", "edtBPNMT")
        '-------------------------------------------------------------------------------
        '폼콘트롤과 UserDateSource 바인딩 끝
        '-------------------------------------------------------------------------------

        '-------------------------------------------------------------------------------
        '그리드를 위한 데이터 테이블 선어 및 바인딩 시작
        '-------------------------------------------------------------------------------
        Call oForm.DataSources.DataTables.Add("grdDETAIL")

        Dim oGrid As SAPbouiCOM.Grid = oForm.Items.Item("grdDETAIL").Specific

        oGrid.DataTable = oForm.DataSources.DataTables.Item("grdDETAIL")

        '-------------------------------------------------------------------------------
        '그리드를 위한 데이터 테이블 선어 및 바인딩 끝
        '-------------------------------------------------------------------------------

        '선언한 객체를 해제
        oGrid = Nothing

    End Sub
    Private Sub Form_Default(ByVal oForm As SAPbouiCOM.Form, Optional ByVal pParm As Object = Nothing)

        Dim oRS As SAPbobsCOM.Recordset = Nothing
        Dim i As Integer = 0
        Dim oComboBox As SAPbouiCOM.ComboBox = Nothing
        Dim xSQL As String = ""

        Dim sParm(9) As String


        If pParm Is Nothing Then
            sParm(0) = ""
            sParm(1) = ""
            sParm(2) = ""
            sParm(3) = ""
            sParm(4) = ""
            sParm(5) = ""
            sParm(6) = ""
            sParm(7) = ""
            sParm(8) = ""
            sParm(9) = ""
        Else
            sParm(0) = pParm(0)
            sParm(1) = pParm(1)
            sParm(2) = pParm(2)
            sParm(3) = pParm(3)
            sParm(4) = pParm(4)
            sParm(5) = pParm(5)
            sParm(6) = pParm(6)
            sParm(7) = pParm(7)
            sParm(8) = pParm(8)
            sParm(9) = pParm(9)
        End If

        Try
            oForm.Freeze(True)

            '-------------------------------------------------------------------------------
            '전기일에 기본 날짜 셋팅하기 시작
            '-------------------------------------------------------------------------------
            If sParm(0) <> "" Then
                oForm.Items.Item("edtDATEF").Specific.string = sParm(0)
            Else
                oForm.Items.Item("edtDATEF").Specific.string = "01"
            End If

            If sParm(1) <> "" Then
                oForm.Items.Item("edtDATET").Specific.value = sParm(1)
            Else
                oForm.Items.Item("edtDATET").Specific.value = Date.Now.ToString("yyyyMMdd")
            End If

            '-------------------------------------------------------------------------------
            '전기일에 기본 날짜 셋팅하기 끝
            '-------------------------------------------------------------------------------

            oRS = B1Connections.diCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.BoRecordset)

            '-------------------------------------------------------------------------------
            '계정유형 콤보셋팅 시작
            '-------------------------------------------------------------------------------
            oComboBox = oForm.Items.Item("cboACTTYPE").Specific

            oRS.DoQuery("SELECT GroupMask, AcctName FROM OACT WHERE Levels = '1'")

            oComboBox.ValidValues.Add("", "전체")

            For i = 0 To oRS.RecordCount - 1
                oComboBox.ValidValues.Add(oRS.Fields.Item("GroupMask").Value, oRS.Fields.Item("AcctName").Value)
                oRS.MoveNext()
            Next

            If sParm(2) <> "" Then
                oComboBox.Select(sParm(2), BoSearchKey.psk_ByValue)
            Else
                oComboBox.Select(0, BoSearchKey.psk_Index) '콤보리스트에 등록된 리스트의 첫번째(0번째 인덱스)값을 선택
            End If


            '-------------------------------------------------------------------------------
            '계정유형 콤보셋팅 시작
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            '계정레벨 콤보셋팅 시작
            '-------------------------------------------------------------------------------
            oComboBox = oForm.Items.Item("cboACTLVL").Specific

            oRS.DoQuery("SELECT Levels FROM OACT Group By Levels ORDER BY Levels")

            oComboBox.ValidValues.Add("", "전체")

            For i = 0 To oRS.RecordCount - 1
                oComboBox.ValidValues.Add(oRS.Fields.Item("Levels").Value, oRS.Fields.Item("Levels").Value)
                oRS.MoveNext()
            Next

            If sParm(3) <> "" Then
                oComboBox.Select(sParm(3), BoSearchKey.psk_ByValue)
            Else
                oComboBox.Select(0, BoSearchKey.psk_Index) '콤보리스트에 등록된 리스트의 첫번째(0번째 인덱스)값을 선택
            End If


            '-------------------------------------------------------------------------------
            '계정레벨 콤보셋팅 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            'BP유형 콤보셋팅 시작
            '-------------------------------------------------------------------------------
            oComboBox = oForm.Items.Item("cboBPTYPE").Specific

            oComboBox.ValidValues.Add("", "전체")
            oComboBox.ValidValues.Add("C", "고객")
            oComboBox.ValidValues.Add("S", "공급업체")
            oComboBox.ValidValues.Add("L", "리드")

            If sParm(4) <> "" Then
                oComboBox.Select(sParm(4), BoSearchKey.psk_ByValue)
            Else
                oComboBox.Select(0, BoSearchKey.psk_Index) '콤보리스트에 등록된 리스트의 첫번째(0번째 인덱스)값을 선택
            End If

            '-------------------------------------------------------------------------------
            'BP유형 콤보셋팅 끝
            '-------------------------------------------------------------------------------

            oComboBox = oForm.Items.Item("cboBPGRP").Specific

            If sParm(5) <> "" Then
                oComboBox.Select(sParm(5), BoSearchKey.psk_ByValue)
            End If

            If sParm(6) <> "" Then
                oForm.DataSources.UserDataSources.Item("edtACCTCDF").Value = sParm(6)
                oForm.DataSources.UserDataSources.Item("edtACCTCDT").Value = sParm(6)
            End If

            If sParm(7) <> "" Then
                oForm.DataSources.UserDataSources.Item("edtACCTNMF").Value = sParm(7)
                oForm.DataSources.UserDataSources.Item("edtACCTNMT").Value = sParm(7)
            End If

            If sParm(8) <> "" Then
                oForm.DataSources.UserDataSources.Item("edtBPCDF").Value = sParm(8)
                oForm.DataSources.UserDataSources.Item("edtBPCDT").Value = sParm(8)
            End If

            If sParm(9) <> "" Then
                oForm.DataSources.UserDataSources.Item("edtBPNMF").Value = sParm(9)
                oForm.DataSources.UserDataSources.Item("edtBPNMT").Value = sParm(9)
            End If

            'oGrid.Columns.Item("TransID").TitleObject.Caption = "분개번호"
            'oGrid.Columns.Item("Line_ID").TitleObject.Caption = "라인번호"
            'oGrid.Columns.Item("TransType").TitleObject.Caption = "문서유형"
            'oGrid.Columns.Item("BaseRef").TitleObject.Caption = "원천문서"

            If sParm(6) = "" Then
                '-------------------------------------------------------------------------------
                '그리드에 기본컬럼값 설정 시작
                '-------------------------------------------------------------------------------
                xSQL = ""
                xSQL = xSQL & "SELECT 	''  AS Account," & vbCrLf
                xSQL = xSQL & "		    ''  AS AcctName," & vbCrLf
                xSQL = xSQL & "		    ''  AS CardCode," & vbCrLf
                xSQL = xSQL & "		    ''  AS CardName," & vbCrLf
                xSQL = xSQL & "		    ''  AS TransID," & vbCrLf
                xSQL = xSQL & "		    ''  AS Line_ID," & vbCrLf
                xSQL = xSQL & "		    ''  AS TransType," & vbCrLf
                xSQL = xSQL & "		    ''  AS BaseRef," & vbCrLf
                xSQL = xSQL & "		    ''  AS RefDate," & vbCrLf
                xSQL = xSQL & "		    ''  AS DueDate," & vbCrLf
                xSQL = xSQL & "		    ''  AS TaxDate," & vbCrLf
                xSQL = xSQL & "		    ''  AS Memo," & vbCrLf
                xSQL = xSQL & "		    0  AS Debit," & vbCrLf
                xSQL = xSQL & "		    0  AS Credit," & vbCrLf
                xSQL = xSQL & "		    0  AS FCDebit," & vbCrLf
                xSQL = xSQL & "		    0  AS FCCredit," & vbCrLf
                xSQL = xSQL & "		    0  AS SYSDeb," & vbCrLf
                xSQL = xSQL & "		    0  AS SYSCred" & vbCrLf

                Find_grdDETAIL(oForm, xSQL)
                '-------------------------------------------------------------------------------
                '그리드에 기본컬럼값 설정 끝
                '-------------------------------------------------------------------------------
            End If

        Catch ex As Exception
            CFL.COMMON_MESSAGE("!", ex.Message)
        Finally
            oForm.Freeze(False)
        End Try
    End Sub
#Region "IDisposable...."
    Protected Overridable Sub Dispose(ByVal disposing As [Boolean])
        If (disposedValue = False) Then
            If (disposing = True) Then
                'TODO: free unmanaged resources when explicitly called
            End If
            'TODO: free shared unmanaged resources
            Me.ClearUnManagedObject()
        End If
        disposedValue = True
    End Sub

    Sub IDisposable_Dispose() Implements IDisposable.Dispose
        Me.Dispose(True)
        GC.SuppressFinalize(Me)
    End Sub
#End Region


    Private Sub AddChooseFromList(ByVal oForm As SAPbouiCOM.Form)

        Dim oCFL As SAPbouiCOM.ChooseFromList
        Dim oCFLCreationParams As SAPbouiCOM.ChooseFromListCreationParams
        Dim oCons As SAPbouiCOM.Conditions
        Dim oCon As SAPbouiCOM.Condition

        Try

            '-------------------------------------------------------------------------------
            '계정시작 ChooseFromList 셋팅 시작
            '-------------------------------------------------------------------------------

            oCFLCreationParams = B1Connections.theAppl.CreateObject(SAPbouiCOM.BoCreatableObjectType.cot_ChooseFromListCreationParams)

            oCFLCreationParams.ObjectType = BoLinkedObject.lf_GLAccounts

            oCFLCreationParams.UniqueID = "edtACCTCDF"

            oCFL = oForm.ChooseFromLists.Add(oCFLCreationParams)

            oCons = oCFL.GetConditions()

            oCon = oCons.Add()
            oCon.Alias = "Postable"
            oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
            oCon.CondVal = "Y"

            oCFL.SetConditions(oCons)

            oForm.Items.Item("edtACCTCDF").Specific.ChooseFromListUID = "edtACCTCDF"
            oForm.Items.Item("edtACCTCDF").Specific.ChooseFromListAlias = "AcctCode"

            '-------------------------------------------------------------------------------
            '계정시작 ChooseFromList 셋팅 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            '계정끝 ChooseFromList 셋팅 시작
            '-------------------------------------------------------------------------------

            oCFLCreationParams = B1Connections.theAppl.CreateObject(SAPbouiCOM.BoCreatableObjectType.cot_ChooseFromListCreationParams)

            oCFLCreationParams.ObjectType = BoLinkedObject.lf_GLAccounts
            oCFLCreationParams.UniqueID = "edtACCTCDT"

            oCFL = oForm.ChooseFromLists.Add(oCFLCreationParams)

            oCons = oCFL.GetConditions()

            oCon = oCons.Add()
            oCon.Alias = "Postable"
            oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
            oCon.CondVal = "Y"

            oCFL.SetConditions(oCons)

            oForm.Items.Item("edtACCTCDT").Specific.ChooseFromListUID = "edtACCTCDT"
            oForm.Items.Item("edtACCTCDT").Specific.ChooseFromListAlias = "AcctCode"

            '-------------------------------------------------------------------------------
            '계정끝 ChooseFromList 셋팅 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            'BP시작 ChooseFromList 셋팅 시작
            '-------------------------------------------------------------------------------

            oCFLCreationParams = B1Connections.theAppl.CreateObject(SAPbouiCOM.BoCreatableObjectType.cot_ChooseFromListCreationParams)

            oCFLCreationParams.ObjectType = BoLinkedObject.lf_BusinessPartner
            oCFLCreationParams.UniqueID = "edtBPCDF"

            oCFL = oForm.ChooseFromLists.Add(oCFLCreationParams)

            oCons = oCFL.GetConditions()

            oCon = oCons.Add()
            oCon.Alias = "frozenFor"
            oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
            oCon.CondVal = "N"

            oCFL.SetConditions(oCons)

            oForm.Items.Item("edtBPCDF").Specific.ChooseFromListUID = "edtBPCDF"
            oForm.Items.Item("edtBPCDF").Specific.ChooseFromListAlias = "CardCode"

            '-------------------------------------------------------------------------------
            'BP시작 ChooseFromList 셋팅 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            'BP끝 ChooseFromList 셋팅 시작
            '-------------------------------------------------------------------------------

            oCFLCreationParams = B1Connections.theAppl.CreateObject(SAPbouiCOM.BoCreatableObjectType.cot_ChooseFromListCreationParams)

            oCFLCreationParams.ObjectType = BoLinkedObject.lf_BusinessPartner
            oCFLCreationParams.UniqueID = "edtBPCDT"

            oCFL = oForm.ChooseFromLists.Add(oCFLCreationParams)

            oCons = oCFL.GetConditions()

            oCon = oCons.Add()
            oCon.Alias = "frozenFor"
            oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
            oCon.CondVal = "N"

            oCFL.SetConditions(oCons)

            oForm.Items.Item("edtBPCDT").Specific.ChooseFromListUID = "edtBPCDT"
            oForm.Items.Item("edtBPCDT").Specific.ChooseFromListAlias = "CardCode"

            '-------------------------------------------------------------------------------
            'BP끝 ChooseFromList 셋팅 끝
            '-------------------------------------------------------------------------------

        Catch ex As Exception

            B1Connections.theAppl.StatusBar.SetText("AddChooseFromList " & Err.Description, SAPbouiCOM.BoMessageTime.bmt_Short, SAPbouiCOM.BoStatusBarMessageType.smt_Error)

        Finally

            oCFLCreationParams = Nothing
            oCFL = Nothing
            oCons = Nothing
            oCon = Nothing

        End Try

    End Sub


    <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, False, ActionType.Itm, "edtACCTCDF")> _
    Public Overridable Sub ET_edtACCTCDF_AFChooseFromList(ByVal pVal As ItemEvent)
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oEditText = CType(CType(oForm.Items.Item("edtACCTCDF"), SAPbouiCOM.Item).Specific, EditText)
        'ADD YOUR ACTION CODE HERE ...

        Dim oDataTable As SAPbouiCOM.DataTable              '데이터를 가져오기 위해 데이터테이블 추가

        Try
            '데이터 테이블을 ChooseFromList에 선택된 오브젝트에서 가져오도록 세팅
            oDataTable = pVal.SelectedObjects

            '사용자가 ChooseFromList의 취소 버튼을 눌렀을 경우 에러처리(데이터 테이블의 값으로 체크)
            If Not oDataTable Is Nothing Then

                oForm.DataSources.UserDataSources.Item("edtACCTCDF").ValueEx = oDataTable.GetValue("AcctCode", 0).ToString
                oForm.DataSources.UserDataSources.Item("edtACCTNMF").ValueEx = oDataTable.GetValue("AcctName", 0).ToString

            End If
        Catch ex As Exception
            B1Connections.theAppl.StatusBar.SetText("ET_edtSALEPCD_AFChooseFromList " & Err.Description, SAPbouiCOM.BoMessageTime.bmt_Short, SAPbouiCOM.BoStatusBarMessageType.smt_Error)
        Finally
            oDataTable = Nothing
        End Try

    End Sub

    <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, False, ActionType.Itm, "edtACCTCDT")> _
    Public Overridable Sub ET_edtACCTCDT_AFChooseFromList(ByVal pVal As ItemEvent)
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oEditText = CType(CType(oForm.Items.Item("edtACCTCDT"), SAPbouiCOM.Item).Specific, EditText)
        'ADD YOUR ACTION CODE HERE ...

        Dim oDataTable As SAPbouiCOM.DataTable              '데이터를 가져오기 위해 데이터테이블 추가

        Try
            '데이터 테이블을 ChooseFromList에 선택된 오브젝트에서 가져오도록 세팅
            oDataTable = pVal.SelectedObjects

            '사용자가 ChooseFromList의 취소 버튼을 눌렀을 경우 에러처리(데이터 테이블의 값으로 체크)
            If Not oDataTable Is Nothing Then

                oForm.DataSources.UserDataSources.Item("edtACCTCDT").ValueEx = oDataTable.GetValue("AcctCode", 0).ToString
                oForm.DataSources.UserDataSources.Item("edtACCTNMT").ValueEx = oDataTable.GetValue("AcctName", 0).ToString

            End If
        Catch ex As Exception
            B1Connections.theAppl.StatusBar.SetText("ET_edtSALEPCD_AFChooseFromList " & Err.Description, SAPbouiCOM.BoMessageTime.bmt_Short, SAPbouiCOM.BoStatusBarMessageType.smt_Error)
        Finally
            oDataTable = Nothing
        End Try
    End Sub


    <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, False, ActionType.Itm, "edtBPCDF")> _
        Public Overridable Sub ET_edtBPCDF_AFChooseFromList(ByVal pVal As ItemEvent)
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oEditText = CType(CType(oForm.Items.Item("edtBPCDF"), SAPbouiCOM.Item).Specific, EditText)
        'ADD YOUR ACTION CODE HERE ...

        Dim oDataTable As SAPbouiCOM.DataTable              '데이터를 가져오기 위해 데이터테이블 추가

        Try
            '데이터 테이블을 ChooseFromList에 선택된 오브젝트에서 가져오도록 세팅
            oDataTable = pVal.SelectedObjects

            '사용자가 ChooseFromList의 취소 버튼을 눌렀을 경우 에러처리(데이터 테이블의 값으로 체크)
            If Not oDataTable Is Nothing Then

                oForm.DataSources.UserDataSources.Item("edtBPCDF").ValueEx = oDataTable.GetValue("CardCode", 0).ToString
                oForm.DataSources.UserDataSources.Item("edtBPNMF").ValueEx = oDataTable.GetValue("CardName", 0).ToString

            End If
        Catch ex As Exception
            B1Connections.theAppl.StatusBar.SetText("ET_edtSALEPCD_AFChooseFromList " & Err.Description, SAPbouiCOM.BoMessageTime.bmt_Short, SAPbouiCOM.BoStatusBarMessageType.smt_Error)
        Finally
            oDataTable = Nothing
        End Try

    End Sub

    <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, False, ActionType.Itm, "edtBPCDT")> _
        Public Overridable Sub ET_edtBPCDT_AFChooseFromList(ByVal pVal As ItemEvent)
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oEditText = CType(CType(oForm.Items.Item("edtBPCDT"), SAPbouiCOM.Item).Specific, EditText)
        'ADD YOUR ACTION CODE HERE ...

        Dim oDataTable As SAPbouiCOM.DataTable              '데이터를 가져오기 위해 데이터테이블 추가

        Try
            '데이터 테이블을 ChooseFromList에 선택된 오브젝트에서 가져오도록 세팅
            oDataTable = pVal.SelectedObjects

            '사용자가 ChooseFromList의 취소 버튼을 눌렀을 경우 에러처리(데이터 테이블의 값으로 체크)
            If Not oDataTable Is Nothing Then

                oForm.DataSources.UserDataSources.Item("edtBPCDT").ValueEx = oDataTable.GetValue("CardCode", 0).ToString
                oForm.DataSources.UserDataSources.Item("edtBPNMT").ValueEx = oDataTable.GetValue("CardName", 0).ToString

            End If
        Catch ex As Exception
            B1Connections.theAppl.StatusBar.SetText("ET_edtSALEPCD_AFChooseFromList " & Err.Description, SAPbouiCOM.BoMessageTime.bmt_Short, SAPbouiCOM.BoStatusBarMessageType.smt_Error)
        Finally
            oDataTable = Nothing
        End Try
    End Sub


    <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, True, ActionType.Itm, "edtACCTCDF")> _
    Public Overridable Function ET_edtACCTCDF_BFChooseFromList(ByVal pVal As ItemEvent) As Boolean
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oEditText = CType(CType(oForm.Items.Item("edtACCTCDF"), SAPbouiCOM.Item).Specific, EditText)
        'ADD YOUR ACTION CODE HERE ...

        Dim oCFL As SAPbouiCOM.ChooseFromList
        Dim oCFLEvento As SAPbouiCOM.IChooseFromListEvent
        Dim oCFLCreationParams As SAPbouiCOM.ChooseFromListCreationParams
        Dim oCons As SAPbouiCOM.Conditions = New SAPbouiCOM.Conditions()
        Dim oCon As SAPbouiCOM.Condition

        Try
            oCFLCreationParams = B1Connections.theAppl.CreateObject(SAPbouiCOM.BoCreatableObjectType.cot_ChooseFromListCreationParams)


            oCFLEvento = pVal

            oCFL = oForm.ChooseFromLists.Item(oCFLEvento.ChooseFromListUID)

            '-------------------------------------------------------------------------------
            '활성계정만 보기 시작
            '-------------------------------------------------------------------------------
            oCon = oCons.Add()
            oCon.Alias = "Postable"
            oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
            oCon.CondVal = "Y"
            '-------------------------------------------------------------------------------
            '활성계정만 보기 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            '계정유형이 전체가 아닌경우 조건추가 시작
            '-------------------------------------------------------------------------------
            If oForm.DataSources.UserDataSources.Item("cboACTTYPE").Value <> "" Then
                oCon.Relationship = BoConditionRelationship.cr_AND
                oCon = oCons.Add()
                oCon.Alias = "GroupMask"
                oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
                oCon.CondVal = oForm.DataSources.UserDataSources.Item("cboACTTYPE").Value.Trim()
            End If
            '-------------------------------------------------------------------------------
            '계정유형이 전체가 아닌경우 조건추가 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            '계정레벨이 전체가 아닌경우 조건추가 시작
            '-------------------------------------------------------------------------------
            If oForm.DataSources.UserDataSources.Item("cboACTLVL").Value <> "" Then
                oCon.Relationship = BoConditionRelationship.cr_AND
                oCon = oCons.Add()
                oCon.Alias = "Levels"
                oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
                oCon.CondVal = oForm.DataSources.UserDataSources.Item("cboACTLVL").Value.Trim()
            End If
            '-------------------------------------------------------------------------------
            '계정레벨이 전체가 아닌경우 조건추가 끝
            '-------------------------------------------------------------------------------

            oCFL.SetConditions(oCons)

        Catch ex As Exception
            B1Connections.theAppl.StatusBar.SetText("ET_edtACCTCDF_BFChooseFromList " & Err.Description, SAPbouiCOM.BoMessageTime.bmt_Short, SAPbouiCOM.BoStatusBarMessageType.smt_Error)
        Finally
            oCFL = Nothing
            oCFLEvento = Nothing
            oCFLCreationParams = Nothing
            oCons = Nothing
            oCon = Nothing
        End Try

        Return True

    End Function


    <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, True, ActionType.Itm, "edtACCTCDT")> _
    Public Overridable Function ET_edtACCTCDT_BFChooseFromList(ByVal pVal As ItemEvent) As Boolean
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oEditText = CType(CType(oForm.Items.Item("edtACCTCDT"), SAPbouiCOM.Item).Specific, EditText)
        'ADD YOUR ACTION CODE HERE ...

        Dim oCFL As SAPbouiCOM.ChooseFromList
        Dim oCFLEvento As SAPbouiCOM.IChooseFromListEvent
        Dim oCFLCreationParams As SAPbouiCOM.ChooseFromListCreationParams
        Dim oCons As SAPbouiCOM.Conditions = New SAPbouiCOM.Conditions()
        Dim oCon As SAPbouiCOM.Condition

        Try
            oCFLCreationParams = B1Connections.theAppl.CreateObject(SAPbouiCOM.BoCreatableObjectType.cot_ChooseFromListCreationParams)


            oCFLEvento = pVal

            oCFL = oForm.ChooseFromLists.Item(oCFLEvento.ChooseFromListUID)

            '-------------------------------------------------------------------------------
            '활성계정만 보기 시작
            '-------------------------------------------------------------------------------
            oCon = oCons.Add()
            oCon.Alias = "Postable"
            oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
            oCon.CondVal = "Y"
            '-------------------------------------------------------------------------------
            '활성계정만 보기 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            '계정유형이 전체가 아닌경우 조건추가 시작
            '-------------------------------------------------------------------------------
            If oForm.DataSources.UserDataSources.Item("cboACTTYPE").Value <> "" Then
                oCon.Relationship = BoConditionRelationship.cr_AND
                oCon = oCons.Add()
                oCon.Alias = "GroupMask"
                oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
                oCon.CondVal = oForm.DataSources.UserDataSources.Item("cboACTTYPE").Value.Trim()
            End If
            '-------------------------------------------------------------------------------
            '계정유형이 전체가 아닌경우 조건추가 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            '계정레벨이 전체가 아닌경우 조건추가 시작
            '-------------------------------------------------------------------------------
            If oForm.DataSources.UserDataSources.Item("cboACTLVL").Value <> "" Then
                oCon.Relationship = BoConditionRelationship.cr_AND
                oCon = oCons.Add()
                oCon.Alias = "Levels"
                oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
                oCon.CondVal = oForm.DataSources.UserDataSources.Item("cboACTLVL").Value.Trim()
            End If
            '-------------------------------------------------------------------------------
            '계정레벨이 전체가 아닌경우 조건추가 끝
            '-------------------------------------------------------------------------------

            oCFL.SetConditions(oCons)

        Catch ex As Exception
            B1Connections.theAppl.StatusBar.SetText("ET_edtACCTCDF_BFChooseFromList " & Err.Description, SAPbouiCOM.BoMessageTime.bmt_Short, SAPbouiCOM.BoStatusBarMessageType.smt_Error)
        Finally
            oCFL = Nothing
            oCFLEvento = Nothing
            oCFLCreationParams = Nothing
            oCons = Nothing
            oCon = Nothing
        End Try

        Return True

    End Function

    <B1Listener(BoEventTypes.et_COMBO_SELECT, False, ActionType.Itm, "cboBPTYPE")> _
    Public Overridable Sub ET_cboBPTYPE_AFComboSelect(ByVal pVal As ItemEvent)
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oComboBox = CType(CType(oForm.Items.Item("cboBPTYPE"), SAPbouiCOM.Item).Specific, ComboBox)
        'ADD YOUR ACTION CODE HERE ...

        Dim oRS As SAPbobsCOM.Recordset = Nothing

        Try
            oForm.Freeze(True)

            oComboBox = oForm.Items.Item("cboBPGRP").Specific

            For i As Integer = 0 To oComboBox.ValidValues.Count - 1
                oComboBox.ValidValues.Remove(0, BoSearchKey.psk_Index)
            Next



            oRS = B1Connections.diCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.BoRecordset)

            oRS.DoQuery("SELECT GroupCode, GroupName FROM OCRG WHERE GroupType = '" & oForm.DataSources.UserDataSources.Item("cboBPTYPE").Value.Trim & "'")

            oComboBox.ValidValues.Add("", "전체")

            For i As Integer = 0 To oRS.RecordCount - 1
                oComboBox.ValidValues.Add(oRS.Fields.Item("GroupCode").Value, oRS.Fields.Item("GroupName").Value)
                oRS.MoveNext()
            Next

            oForm.DataSources.UserDataSources.Item("cboBPGRP").Value = ""

        Catch ex As Exception

        Finally
            oForm.Freeze(False)

            oRS = Nothing
        End Try


    End Sub


    Private Sub Find_grdDETAIL(ByVal oForm As SAPbouiCOM.Form, ByVal xSQL As String)

        Dim oGrid As SAPbouiCOM.Grid = Nothing
        Dim i As Integer = 0
        Dim oProgBar As SAPbouiCOM.ProgressBar = Nothing
        Dim G_Sum As SAPbouiCOM.EditTextColumn

        oForm.Freeze(True)

        Try

            oProgBar = B1Connections.theAppl.StatusBar.CreateProgressBar("처리중입니다...", 10, False)

            oProgBar.Value = 1

            oGrid = oForm.Items.Item("grdDETAIL").Specific

            oGrid.DataTable.Clear()

            oGrid.DataTable.ExecuteQuery(xSQL)

            oGrid.Columns.Item("Account").TitleObject.Caption = "계정코드"
            oGrid.Columns.Item("AcctName").TitleObject.Caption = "계정명"
            oGrid.Columns.Item("CardCode").TitleObject.Caption = "BP명"
            oGrid.Columns.Item("CardName").TitleObject.Caption = "BP코드"

            oGrid.Columns.Item("TransID").TitleObject.Caption = "분개번호"
            oGrid.Columns.Item("Line_ID").TitleObject.Caption = "라인번호"
            oGrid.Columns.Item("TransType").TitleObject.Caption = "문서유형"
            oGrid.Columns.Item("BaseRef").TitleObject.Caption = "원천문서"

            oGrid.Columns.Item("RefDate").TitleObject.Caption = "전기일"
            oGrid.Columns.Item("DueDate").TitleObject.Caption = "만기일"
            oGrid.Columns.Item("TaxDate").TitleObject.Caption = "만기일"
            oGrid.Columns.Item("Memo").TitleObject.Caption = "비고"
            oGrid.Columns.Item("Debit").TitleObject.Caption = "차변(LC)"
            oGrid.Columns.Item("Credit").TitleObject.Caption = "대변LC)"
            oGrid.Columns.Item("FCDebit").TitleObject.Caption = "차변(FC)"
            oGrid.Columns.Item("FCCredit").TitleObject.Caption = "대변FC)"
            oGrid.Columns.Item("SYSDeb").TitleObject.Caption = "차변(SC)"
            oGrid.Columns.Item("SYSCred").TitleObject.Caption = "대변SC)"

            For i = 12 To oGrid.Columns.Count - 1
                oGrid.Columns.Item(i).RightJustified = True
            Next

            oGrid.Columns.Item("Account").LinkedObjectType = BoLinkedObject.lf_GLAccounts
            oGrid.Columns.Item("CardCode").LinkedObjectType = BoLinkedObject.lf_BusinessPartner
            oGrid.Columns.Item("TransID").LinkedObjectType = BoLinkedObject.lf_JournalPosting
            oGrid.Columns.Item("BaseRef").LinkedObjectType = BoLinkedObject.lf_JournalPosting

            oGrid.Columns.Item("Account").TitleObject.Sortable = True
            oGrid.Columns.Item("AcctName").TitleObject.Sortable = True
            oGrid.Columns.Item("CardCode").TitleObject.Sortable = True
            oGrid.Columns.Item("CardName").TitleObject.Sortable = True

            For i = 12 To oGrid.Columns.Count - 1
                G_Sum = oGrid.Columns.Item(i)
                G_Sum.ColumnSetting.SumType = BoColumnSumType.bst_Auto
                G_Sum = Nothing
            Next

            oGrid.Columns.Item("Account").BackColor = &HCFE3F4
            oGrid.Columns.Item("AcctName").BackColor = &HCFE3F4
            oGrid.Columns.Item("CardCode").BackColor = &HC2F7F9
            oGrid.Columns.Item("CardName").BackColor = &HC2F7F9

            oGrid.CommonSetting.FixedColumnsCount = 8

            oGrid.AutoResizeColumns()

            oProgBar.Value = 10
            oProgBar.Stop()



        Catch ex As Exception

        Finally

            oForm.Freeze(False)
            oForm.Update()

            oGrid = Nothing

            Marshal.ReleaseComObject(oProgBar)
            oProgBar = Nothing

        End Try
    End Sub



    <B1Listener(BoEventTypes.et_ITEM_PRESSED, False, ActionType.Itm, "btnFIND")> _
    Public Overridable Sub ET_btnFIND_AFItemPressed(ByVal pVal As ItemEvent)
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oButton = CType(CType(oForm.Items.Item("btnFIND"), SAPbouiCOM.Item).Specific, Button)
        'ADD YOUR ACTION CODE HERE ...

        Dim xSQL As String = ""

        '-------------------------------------------------------------------------------
        '계정별 그리드 조회 시작
        '-------------------------------------------------------------------------------
        xSQL = ""
        xSQL = xSQL & "EXEC WJS_SP_FIF0011F "
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("edtDATEF").ValueEx.Trim & "',"
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("edtDATET").ValueEx.Trim & "',"
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("cboACTTYPE").ValueEx.Trim & "',"
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("cboACTLVL").ValueEx.Trim & "',"
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("cboBPTYPE").ValueEx.Trim & "',"
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("cboBPGRP").ValueEx.Trim & "',"
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("edtACCTCDF").ValueEx.Trim & "',"
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("edtACCTCDT").ValueEx.Trim & "',"
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("edtBPCDF").ValueEx.Trim & "',"
        xSQL = xSQL & "'" & oForm.DataSources.UserDataSources.Item("edtBPCDT").ValueEx.Trim & "'"


        Find_grdDETAIL(oForm, xSQL)
        '-------------------------------------------------------------------------------
        '계정별 그리드 조회 끝
        '-------------------------------------------------------------------------------

    End Sub



    <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, True, ActionType.Itm, "edtBPCDF")> _
    Public Overridable Function ET_edtBPCDF_BFChooseFromList(ByVal pVal As ItemEvent) As Boolean
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oEditText = CType(CType(oForm.Items.Item("edtBPCDF"), SAPbouiCOM.Item).Specific, EditText)
        'ADD YOUR ACTION CODE HERE ...



        Dim oCFL As SAPbouiCOM.ChooseFromList
        Dim oCFLEvento As SAPbouiCOM.IChooseFromListEvent
        Dim oCFLCreationParams As SAPbouiCOM.ChooseFromListCreationParams
        Dim oCons As SAPbouiCOM.Conditions = New SAPbouiCOM.Conditions()
        Dim oCon As SAPbouiCOM.Condition

        Try
            oCFLCreationParams = B1Connections.theAppl.CreateObject(SAPbouiCOM.BoCreatableObjectType.cot_ChooseFromListCreationParams)


            oCFLEvento = pVal

            oCFL = oForm.ChooseFromLists.Item(oCFLEvento.ChooseFromListUID)

            '-------------------------------------------------------------------------------
            '활성BP만 보기 시작
            '-------------------------------------------------------------------------------
            oCon = oCons.Add()
            oCon.Alias = "frozenFor"
            oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
            oCon.CondVal = "N"
            '-------------------------------------------------------------------------------
            '활성BP만 보기 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            'BP유형이 전체가 아닌경우 조건추가 시작
            '-------------------------------------------------------------------------------
            If oForm.DataSources.UserDataSources.Item("cboBPTYPE").Value <> "" Then
                oCon.Relationship = BoConditionRelationship.cr_AND
                oCon = oCons.Add()
                oCon.Alias = "CardType"
                oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
                oCon.CondVal = oForm.DataSources.UserDataSources.Item("cboBPTYPE").Value.Trim()
            End If
            '-------------------------------------------------------------------------------
            'BP유형이 전체가 아닌경우 조건추가 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            'BP그룹이 전체가 아닌경우 조건추가 시작
            '-------------------------------------------------------------------------------
            If oForm.DataSources.UserDataSources.Item("cboBPGRP").Value <> "" Then
                oCon.Relationship = BoConditionRelationship.cr_AND
                oCon = oCons.Add()
                oCon.Alias = "GroupCode"
                oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
                oCon.CondVal = oForm.DataSources.UserDataSources.Item("cboBPGRP").Value.Trim()
            End If
            '-------------------------------------------------------------------------------
            'BP그룹이 전체가 아닌경우 조건추가 끝
            '-------------------------------------------------------------------------------

            oCFL.SetConditions(oCons)

        Catch ex As Exception
            B1Connections.theAppl.StatusBar.SetText("ET_edtACCTCDF_BFChooseFromList " & Err.Description, SAPbouiCOM.BoMessageTime.bmt_Short, SAPbouiCOM.BoStatusBarMessageType.smt_Error)
        Finally
            oCFL = Nothing
            oCFLEvento = Nothing
            oCFLCreationParams = Nothing
            oCons = Nothing
            oCon = Nothing
        End Try

        Return True
    End Function


    <B1Listener(BoEventTypes.et_CHOOSE_FROM_LIST, True, ActionType.Itm, "edtBPCDT")> _
    Public Overridable Function ET_edtBPCDT_BFChooseFromList(ByVal pVal As ItemEvent) As Boolean
        oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
        oEditText = CType(CType(oForm.Items.Item("edtBPCDT"), SAPbouiCOM.Item).Specific, EditText)
        'ADD YOUR ACTION CODE HERE ...



        Dim oCFL As SAPbouiCOM.ChooseFromList
        Dim oCFLEvento As SAPbouiCOM.IChooseFromListEvent
        Dim oCFLCreationParams As SAPbouiCOM.ChooseFromListCreationParams
        Dim oCons As SAPbouiCOM.Conditions = New SAPbouiCOM.Conditions()
        Dim oCon As SAPbouiCOM.Condition

        Try
            oCFLCreationParams = B1Connections.theAppl.CreateObject(SAPbouiCOM.BoCreatableObjectType.cot_ChooseFromListCreationParams)


            oCFLEvento = pVal

            oCFL = oForm.ChooseFromLists.Item(oCFLEvento.ChooseFromListUID)

            '-------------------------------------------------------------------------------
            '활성BP만 보기 시작
            '-------------------------------------------------------------------------------
            oCon = oCons.Add()
            oCon.Alias = "frozenFor"
            oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
            oCon.CondVal = "N"
            '-------------------------------------------------------------------------------
            '활성BP만 보기 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            'BP유형이 전체가 아닌경우 조건추가 시작
            '-------------------------------------------------------------------------------
            If oForm.DataSources.UserDataSources.Item("cboBPTYPE").Value <> "" Then
                oCon.Relationship = BoConditionRelationship.cr_AND
                oCon = oCons.Add()
                oCon.Alias = "CardType"
                oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
                oCon.CondVal = oForm.DataSources.UserDataSources.Item("cboBPTYPE").Value.Trim()
            End If
            '-------------------------------------------------------------------------------
            'BP유형이 전체가 아닌경우 조건추가 끝
            '-------------------------------------------------------------------------------

            '-------------------------------------------------------------------------------
            'BP그룹이 전체가 아닌경우 조건추가 시작
            '-------------------------------------------------------------------------------
            If oForm.DataSources.UserDataSources.Item("cboBPGRP").Value <> "" Then
                oCon.Relationship = BoConditionRelationship.cr_AND
                oCon = oCons.Add()
                oCon.Alias = "GroupCode"
                oCon.Operation = SAPbouiCOM.BoConditionOperation.co_EQUAL
                oCon.CondVal = oForm.DataSources.UserDataSources.Item("cboBPGRP").Value.Trim()
            End If
            '-------------------------------------------------------------------------------
            'BP그룹이 전체가 아닌경우 조건추가 끝
            '-------------------------------------------------------------------------------

            oCFL.SetConditions(oCons)

        Catch ex As Exception
            B1Connections.theAppl.StatusBar.SetText("ET_edtACCTCDF_BFChooseFromList " & Err.Description, SAPbouiCOM.BoMessageTime.bmt_Short, SAPbouiCOM.BoStatusBarMessageType.smt_Error)
        Finally
            oCFL = Nothing
            oCFLEvento = Nothing
            oCFLCreationParams = Nothing
            oCons = Nothing
            oCon = Nothing
        End Try

        Return True
    End Function

    
        <B1Listener(BoEventTypes.et_MATRIX_LINK_PRESSED, true, ActionType.Itm, "grdDETAIL")>  _
        Public Overridable Function ET_grdDETAIL_BFMatrixLinkPressed(ByVal pVal As ItemEvent) As Boolean
            oForm = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            oGrid = CType(CType(oForm.Items.Item("grdDETAIL"),SAPbouiCOM.Item).Specific,Grid)
        'ADD YOUR ACTION CODE HERE ...

        oGrid.Columns.Item("BaseRef").LinkedObjectType = oGrid.DataTable.GetValue("TransType", pVal.Row)

            Return true
        End Function
    
End Class
